source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# engine
gem 'shared', path: '../shared'
eval_gemfile "../shared/Gemfile.shared"

# server
gem 'puma', '~> 4.3'

# controller
gem 'omniauth'
gem 'omniauth-twitter'
gem 'rambulance'

# decorator
gem 'draper'

# view
gem 'haml-rails'

# css preprocessor
gem 'sprockets', '~> 3.0'
gem 'sass'
gem 'rails-uikit'
gem 'uglifier', '>= 1.3.0'

# jquery packages
gem 'jquery-rails'
gem 'modernizr-rails'
gem 'pickadate-rails'
gem 'remodal-rails'
