version: '3'
services:
  app:
    image: 081239106582.dkr.ecr.ap-northeast-1.amazonaws.com/clean_them_all/api:latest
    env_file: ../.env.production
    entrypoint: ["./entrypoint.sh"]
    volumes:
      - bundle:/bundle:cached
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: clean_them_all
        awslogs-stream-prefix: api

volumes:
  bundle:
