source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# engine
gem 'shared', path: '../shared'
eval_gemfile "../shared/Gemfile.shared"

# server
gem 'puma', '~> 3.12'

# controller
gem 'omniauth'
gem 'omniauth-twitter'

# serialize
gem 'active_model_serializers', '~> 0.10.0'
