source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

# engine
gem 'base', path: '../base'

# base
gem 'rails', '~> 5.2.2'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'configatron'

# database
gem 'mysql2'
gem 'ridgepole'

# web
gem 'puma', '~> 3.7'

# model
gem 'aasm'
gem 'active_hash'

# value object
gem 'dry-types'
gem 'dry-struct'

# serialize
gem 'active_model_serializers', '~> 0.10.0'

# form
gem 'reform-rails'
gem 'dry-validation'

# sdk
gem 'aws-sdk-s3'

group :production do
  gem 'bugsnag'
end

# dev utils
group :development do
  gem 'rubocop', require: false
  gem 'annotate'
end

# testing
group :test do
  gem 'nyan-cat-formatter'
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'webmock'
end

# development tools
group :development, :test do
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'byebug'
  gem 'pry-rails'
  gem 'pry-byebug'

  gem 'listen', '>= 3.0.5', '< 3.2'
end
