on:
  push:
    branches:
      - deploy/production
name: Build and Push Image to ECR
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run make build
        run: |
          export ROOT_PATH=$(pwd)
          cd app/backend
          make build
